[package]
name = "rhai-bitsy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rhai = "1.16.3"
bitsy = { path = "../bitsy" }
reqwest = { version = "0.11.23", features = ["blocking"] }
